### ISSUE TITLE
Unable to use DID as /user/

### ISSUE THREAD

**Issue by electricduck** [echo8/pastesphere#1]
While `https://pastesphere.link/user/ducky.ws/snippet/3lcpsko2jqs24` (handle) works, it looks as if `https://pastesphere.link/user/did:plc:kv7sv4lynbv5s6gdhn5r5vcw/snippet/3lcpsko2jqs24` (DID) doesn't. Its standard amongst ATProto apps to allow navigation via both, as DIDs provide a strong unbreakable link to a record.

**Comment by echo8** [comment]
Thanks for pointing this out! I just pushed a fix for this and it should be live now.

I'll also look into changing the 'copy permalink' button to use the DID as well since they are more permanent.

**Comment by echo8** [comment]
And the permalink now uses the DID too.
