### ISSUE TITLE
Light mode uses some dark themeing and is hard to read

### ISSUE THREAD

**Issue by Hoid** [echo8/pastesphere#2]
<img width="1470" alt="Screenshot 2024-12-07 at 10 21 06 AM" src="https://github.com/user-attachments/assets/9849021d-97c3-48b7-b04c-40acb81349ad">

The dark background for the text container was kind of jarring at first, and the text color inside of it is much too dark to read. I'd recommend choosing a slightly lighter grey instead of the dark grey background and changing the text inside to white, when on the light theme, unless you just prefer making the internal background white as well (I confirmed it's on the light theme in the html).

**Comment by echo8** [comment]
Totally forgot to theme the light mode! Will make this actually usable soon.

**Comment by echo8** [comment]
Ok light mode should be usable now.
