### ISSUE TITLE
Skip loading prism styles for known highlighting types

### ISSUE THREAD

**Issue by benharri** [echo8/pastesphere#3]
![image](https://github.com/user-attachments/assets/901b806c-1ee4-4e35-a97d-ee86a9485a38)

here's a sample paste set to C#. shouldn't need to load the styles for all of these other languages
https://pastesphere.link/user/did:plc:v7tbr6qxk6xanxzn6hjmbk7o/snippet/3lcubc6b4js2y

**Comment by echo8** [comment]
Yea definitely want to make this better. Let me play around with how I load the prism styles.

**Comment by echo8** [comment]
Just pushed a fix for this. Now only prism styles that are actually used should be loaded.
